export const beyblades = [
    {"image": require("./images/stormpegasus-takara.png"),
    "series":"Metal Fusion",
    "name":"Storm Pegasus 105RF",
    "type":"Attack",
    "faceBolt":"Pegasus I",
    "energyRing":"Pegasus I",
    "fusionWheel":"Storm",
    "spinTrack":"105",
    "performanceTip":"Rubber Flat"},

    {"image": require("./images/rockleone-takara.png"),
    "series":"Metal Fusion",
    "name":"Rock Leone 145WB",
    "type":"Defense",
    "faceBolt":"Leone I",
    "energyRing":"Leone I",
    "fusionWheel":"Rock",
    "spinTrack":"145",
    "performanceTip":"Wide Ball"},

    {"image": require("./images/lightningldrago-takara.png"),
    "series":"Metal Fusion",
    "name":"Lightning L-Drago 100HF",
    "type":"Attack",
    "faceBolt":"L-Dragon I",
    "energyRing":"L-Dragon I",
    "fusionWheel":"Lightning",
    "spinTrack":"100",
    "performanceTip":"Hollow Flat"},

    {"image": require("./images/flamesagittario-takara.png"),
    "series":"Metal Fusion",
    "name":"Flame Sagittario C145S",
    "type":"Stamina",
    "faceBolt":"Sagittario I",
    "energyRing":"Sagittario I",
    "fusionWheel":"Flame",
    "spinTrack":"Claw 145",
    "performanceTip":"Spike"},

    {"image": require("./images/eartheagle-takara.png"),
    "series":"Metal Fusion",
    "name":"Earth Eagle 145WD",
    "type":"Defense",
    "faceBolt":"Eagle",
    "energyRing":"Eagle",
    "fusionWheel":"Earth",
    "spinTrack":"145",
    "performanceTip":"Wide Defense"},

    {"image": require("./images/galaxypegasus-takara.png"),
    "series":"Metal Masters",
    "name":"Galaxy Pegasus W105R2F",
    "type":"Attack",
    "faceBolt":"Pegasus II",
    "energyRing":"Pegasus II",
    "fusionWheel":"Galaxy",
    "spinTrack":"Wing 105",
    "performanceTip":"R2F"},

    {"image": require("./images/raystriker-takara.png"),
    "series":"Metal Masters",
    "name":"Ray Striker D125CS",
    "type":"Attack",
    "faceBolt":"Striker I",
    "energyRing":"Striker I",
    "fusionWheel":"Ray",
    "spinTrack":"Defense 125",
    "performanceTip":"Coating Spike"},

    {"image": require("./images/meteoldrago-takara.png"),
    "series":"Metal Masters",
    "name":"Meteo L-Drago LW105LF",
    "type":"Attack",
    "faceBolt":"L-Drago II",
    "energyRing":"L-Drago II",
    "fusionWheel":"Meteo",
    "spinTrack":"Left Wing 105",
    "performanceTip":"Left Flat"},

    {"image": require("./images/twistedtempo-takara.png"),
    "series":"Metal Masters",
    "name":"Twisted Tempo 145WD",
    "type":"Defense",
    "faceBolt":"Tempo",
    "energyRing":"Tempo",
    "fusionWheel":"Twisted",
    "spinTrack":"145",
    "performanceTip":"Wide Defense"},

    {"image": require("./images/gravitydestroyer-takara.png"),
    "series":"Metal Masters",
    "name":"Gravity Destroyer AD145WD",
    "type":"Defense",
    "faceBolt":"Destroyer",
    "energyRing":"Destroyer",
    "fusionWheel":"Gravity",
    "spinTrack":"Armor Defense 145",
    "performanceTip":"Wide Defense"},

    {"image": require("./images/cosmicpegasus-takara.png"),
    "series":"Metal Fury",
    "name":"Cosmic Pegasus F:D",
    "type":"Attack",
    "faceBolt":"Pegasus III",
    "energyRing":"Pegasus III",
    "fusionWheel":"Cosmic",
    "spinTrack":"NA",
    "performanceTip":"Final Drive"},

    {"image": require("./images/fangleone-takara.png"),
    "series":"Metal Fury",
    "name":"Fang Leone 130W2D",
    "type":"Defense",
    "faceBolt":"Leone II",
    "energyRing":"Leone II",
    "fusionWheel":"Fang",
    "spinTrack":"130",
    "performanceTip":"Wave Wide Defense"},

    {"image": require("./images/ldragodestructor-takara.png"),
    "series":"Metal Fury",
    "name":"L-Drago Destructor F:S",
    "type":"Attack",
    "faceBolt":"L-Drago III",
    "energyRing":"NA",
    "fusionWheel":"L-Drago Destructor",
    "spinTrack":"NA",
    "performanceTip":"Final Survive"},

    {"image": require("./images/flashsagittario-takara.png"),
    "series":"Metal Fury",
    "name":"Flash Sagittario 230WD",
    "type":"Stamina",
    "faceBolt":"Sagittario II",
    "energyRing":"Sagittario II",
    "fusionWheel":"Flash",
    "spinTrack":"230",
    "performanceTip":"Wide Defense"},

    {"image": require("./images/diablonemesis-takara.png"),
    "series":"Metal Fury",
    "name":"Diablo Nemesis X:D",
    "type":"Balance",
    "faceBolt":"Nemesis A",
    "energyRing":"Nemesis A",
    "fusionWheel":"Diablo",
    "spinTrack":"NA",
    "performanceTip":"X Drive"}
]